FROM node:16

# Install compilers and interpreters
RUN apt-get update && \
    apt-get install -y openjdk-11-jdk gcc g++ python3 && \
    apt-get clean;

# Install bun
RUN curl -fsSL https://bun.sh/install | bash

# Set environment variables for bun
ENV BUN_INSTALL="/root/.bun"
ENV PATH="$BUN_INSTALL/bin:$PATH"

# Set the working directory
WORKDIR .

# Copy application files
COPY . .

# Install dependencies using bun
RUN bun install

# Generate Prisma Client
RUN bun prisma generate

# Push the Prisma schema to the database
RUN bun prisma db push

# Expose the application port
EXPOSE 5000

# Start the application
CMD ["bun", "start"]
